[tool.poetry]
name = "leetcode"
version = "0.1.0"
description = ""
authors = ["Max Fischer"]

[tool.poetry.dependencies]
python = ">=3.9.1,<3.11"
numpy = "^1.21.2"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
